package com.kinship.automation.constants;

public class WhistleConstants {

    public static String ACCEPT_HEADER = "application/vnd.whistle.com.v5+json";
    public static String EMAIL = "hasmukh.patel+API1@kinship.co";
    public static String EMAIL_MOBILE = "wc7@gmail.com";
    public static String PASSWORD = "test1234";
    public static String INVALID_EMAIL = "test@whistle";
    public static String NON_EXISTING_EMAIL = "NonExistingEmail@gmail.com";
    public static String RESET_PASSWORD_LINK_SENT_MSG = "Check your email for your reset password link";
    public static String RESET_PASSWORD_NONEXISTING_EMAIL_MSG = "There was a problem resetting your password, please try again.";
    public static String SUBSCRIPTION_ID = "234";
    public static String NONEXISTING_SUBSCRIPTION_ID = "12";
    public static String PREVIEW_SUBSCRIPTION_ID = "62066";
    public static String SUBSCRIPTION_NOTFOUND_MESSAGE = "Subscription not found";
    public static String NOACTIVE_SUBSCRIPTION_MESSAGE = "Device does not have active subscription";
    public static String SUBSCRIPTION_CANCELLATION_REASON_IDs = "[12, 10, 13, 15, 19, 26, 5, 14, 8, 2, 9, 16, 3, 6, 4, 7, 22, 20, 11]";
    public static String SUBSCRIPTION_CANCELLATION_MESSAGES = "[Already returned the device, Battery didn't last long enough, Change of address, Couldn't activate the device, Device kept falling off my pet, Device was chewed up (damaged), Device was lost, Device was too big, My pet is much older now, My pet passed away, No cellular coverage in my area, Notifications are not fast enough, Not satisified with performance, Only use at certain times of the year, Pet has been trained, Subscription is too expensive, Unhappy with customer support, Unhappy with the mobile application, We built a fence]";
    public static String INVALID_PETID = "456576";
    public static String ERROR_MSG_POWER_SAVING = "[Device is in power-saving mode]";
    public static String ERROR_MSG_DEVICE_NOT_FOUND = "[Device not found]";
    public static String WHISTLE_BLE_DEVICE_MSG = "Location + Health + Fitness";
    public static String WHISTLE_DEVICE_MSG = "Health + Fitness";
    public static String SUBSCRIPTION_STATUS = "active";
    public static String SIGN_IN_TEXT = "Sign in";
    public static String SIGN_IN_MSG = "Have an account? Sign in";
    public static String PET_BREED_NAME="Airedale Terrier";
    public static int BREED_INDEX = 0;
    public static String UPDATE_PET_NAME="Rose";
    public static String UPDATE_PET_SEX = "Female";
    public static String REUPDATE_PET_SEX="Male";
    public static String UPDATE_OLD_PET_NAME = "Kulfi";
    public static String LONG_PET_NAME="Prior to MANTA end-to-end impact and lineage analysis for our Enterprise Data Warehouse was not feasible. It took 6 months to perform a table-level dependency analysis on our EDW and Data Marts. With Manta, that and more was available out-of-box Effort for";
    public static String UPDATE_TIME_ZONE="America/Lima";
    public static String REUPDATE_TIME_ZONE="America/Los_Angeles";
    public static String UPDATE_WEIGHT = "2.0";
    public static String UPDATE_WEIGHT_IOS = "4";
    public static String UPDATE_WEIGHT_DECIMAL = "9.5";
    public static String UPDATE_WEIGHT_ZERO = "0.0";
    public static String PET_FOOD="Acana";
    public static String UPDATE_PET_FOOD="Acana Duck & Pear Formula";
    public static String UPDATE_WEIGHT_GREATERTHAN_MAXVALUEKG = "160";
    public static String UPDATE_WEIGHT_GREATERTHAN_MAXVALUELBS = "351";
    public static String UPDATE_AGE="4";
    public static String UPDATE_AGE_ZERO="0";
    public static String ALL_TAB_NAMES = "Home Activity Location Pet Human";
    public static String AM2_TAB_NAMES = "Home Activity Pet Human";
    public static String LOCATION_TAB_EMPTY_HEADER = "Feature not compatible";
    public static String LOCATION_TAB_EMPTY_HEADER_IOS = "Location not available";
    public static String ADDRESS ="New";
}
